# plot_box_breakdown.py
# ------------------------------------------------------------
# Category D plots: Box error breakdown (class-aware)
# FIXED ORDER: clean baselines first, then blur (perturbation)
#
# Inputs (generated by box_error_breakdown.py):
#   - 640_clean_per_match.csv (optional)
#   - 800_clean_per_match.csv
#   - 800_blur2_per_match.csv
#   - summary.csv
#   - summary_by_bucket.csv
#
# Outputs:
#   - D1_iou_hist_800_clean_vs_blur2.png
#   - D2_median_box_errors_by_condition.png
#   - D3_median_iou_by_bucket.png
# ------------------------------------------------------------

import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# =========================
# PATHS (PREBUILT)
# =========================
IN_DIR = "D:/Desktop/project/workspace/results/box_breakdown"
OUT_DIR = "D:/Desktop/project/figures"
os.makedirs(OUT_DIR, exist_ok=True)

PER_MATCH_FILES = {
    "640_clean": os.path.join(IN_DIR, "640_clean_per_match.csv"),   # optional
    "800_clean": os.path.join(IN_DIR, "800_clean_per_match.csv"),
    "800_blur2": os.path.join(IN_DIR, "800_blur2_per_match.csv"),
}

SUMMARY_CSV = os.path.join(IN_DIR, "summary.csv")
SUMMARY_BUCKET_CSV = os.path.join(IN_DIR, "summary_by_bucket.csv")

# Toggle: include 640_clean in IoU histogram (nice as reference)
INCLUDE_640_IN_HIST = True

# Histogram binning
IOU_BINS = 30

# IMPORTANT: fixed, semantic ordering (baseline -> perturbation)
COND_ORDER = ["640_clean", "800_clean", "800_blur2"]

# =========================
# HELPERS
# =========================
def load_csv_if_exists(path: str):
    return pd.read_csv(path) if os.path.exists(path) else None

def apply_condition_order(df: pd.DataFrame, col: str = "Condition") -> pd.DataFrame:
    """Force semantic condition ordering (baseline -> perturbation)."""
    if col in df.columns:
        df[col] = pd.Categorical(df[col], categories=COND_ORDER, ordered=True)
        df = df.sort_values(col)
    return df


# =============================================================================
# PLOT D1: IoU HISTOGRAM (COUNTS, side-by-side bars)
# =============================================================================
def plot_iou_histogram_side_by_side():
    df_800_clean = load_csv_if_exists(PER_MATCH_FILES["800_clean"])
    df_800_blur2 = load_csv_if_exists(PER_MATCH_FILES["800_blur2"])
    if df_800_clean is None or df_800_blur2 is None:
        raise FileNotFoundError("Missing 800_clean_per_match.csv or 800_blur2_per_match.csv.")

    iou_clean = df_800_clean["IoU"].to_numpy()
    iou_blur = df_800_blur2["IoU"].to_numpy()

    # Common bins
    bin_edges = np.linspace(0.0, 1.0, IOU_BINS + 1)
    centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])
    bin_w = (bin_edges[1] - bin_edges[0])

    # Counts per bin
    clean_counts, _ = np.histogram(iou_clean, bins=bin_edges)
    blur_counts, _ = np.histogram(iou_blur, bins=bin_edges)

    plt.figure(figsize=(8.5, 5.5))

    # Side-by-side: offset by half bar width
    w = 0.45 * bin_w
    plt.bar(centers - w/2, clean_counts, width=w, label="800 clean", alpha=0.9)
    plt.bar(centers + w/2, blur_counts, width=w, label="800 blur (σ=2)", alpha=0.9)

    plt.xlabel("IoU")
    plt.ylabel("Count (matched boxes)")
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend(loc="upper left")
    plt.title("IoU histogram (counts) — 800 clean vs 800 blur (σ=2)", fontsize=12)

    out_path = os.path.join(OUT_DIR, "D1_iou_hist_800_clean_vs_blur2.png")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()
    print("Saved:", out_path)


# =============================================================================
# PLOT D2: MEDIAN BOX ERRORS (summary.csv) (fixed x-axis order)
# =============================================================================
def plot_median_box_errors():
    df = load_csv_if_exists(SUMMARY_CSV)
    if df is None:
        raise FileNotFoundError("summary.csv not found in box_breakdown folder.")

    required = ["Condition", "dx_median", "dy_median", "dw_median", "dh_median", "IoU_median"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise KeyError(f"summary.csv missing columns: {missing}. Found: {df.columns.tolist()}")

    df = apply_condition_order(df, "Condition")
    df = df[df["Condition"].notna()]

    conditions = df["Condition"].astype(str).tolist()

    metrics = ["dx_median", "dy_median", "dw_median", "dh_median"]
    metric_labels = ["|Δx| (center)", "|Δy| (center)", "|Δw| (size)", "|Δh| (size)"]

    x = list(range(len(conditions)))
    bar_w = 0.18

    plt.figure(figsize=(9, 5.5))

    for i, (m, lab) in enumerate(zip(metrics, metric_labels)):
        xpos = [xi + (i - 1.5) * bar_w for xi in x]
        plt.bar(xpos, df[m].values, width=bar_w, label=lab)

    plt.xticks(x, conditions, rotation=0)
    plt.ylabel("Median normalized absolute error")
    plt.grid(True, axis="y", linestyle="--", alpha=0.5)
    plt.legend(loc="upper right")

    plt.title("Median Box Errors by Condition (Class-aware Matching)", fontsize=12)

    out_path = os.path.join(OUT_DIR, "D2_median_box_errors_by_condition.png")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()

    print("Saved:", out_path)


# =============================================================================
# PLOT D3: MEDIAN IoU BY BUCKET (summary_by_bucket.csv) (fixed legend order)
# =============================================================================
def plot_median_iou_by_bucket():
    df = load_csv_if_exists(SUMMARY_BUCKET_CSV)
    if df is None:
        raise FileNotFoundError("summary_by_bucket.csv not found in box_breakdown folder.")

    required = ["Condition", "Bucket", "IoU_median"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise KeyError(f"summary_by_bucket.csv missing columns: {missing}. Found: {df.columns.tolist()}")

    bucket_order = ["S", "M", "L"]
    df["Bucket"] = pd.Categorical(df["Bucket"], categories=bucket_order, ordered=True)

    df = apply_condition_order(df, "Condition")
    df = df[df["Condition"].notna()]

    pivot_iou = df.pivot(index="Bucket", columns="Condition", values="IoU_median")

    existing_cols = [c for c in COND_ORDER if c in pivot_iou.columns]
    pivot_iou = pivot_iou[existing_cols]

    plt.figure(figsize=(8.5, 5.5))
    pivot_iou.plot(kind="bar", ax=plt.gca())

    plt.xlabel("COCO object size bucket")
    plt.ylabel("Median IoU")
    plt.grid(True, axis="y", linestyle="--", alpha=0.5)
    plt.legend(title="Condition", loc="upper left")

    plt.title("Median IoU by Object Size Bucket (Class-aware Matching)", fontsize=12)

    out_path = os.path.join(OUT_DIR, "D3_median_iou_by_bucket.png")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()

    print("Saved:", out_path)


# =============================================================================
# RUN
# =============================================================================
if __name__ == "__main__":
    plot_iou_histogram_side_by_side()
    plot_median_box_errors()
    plot_median_iou_by_bucket()
    print("\nDone.")
